### ISSUE TITLE
Package dependency

### ISSUE THREAD

**Issue by jjchern** [EmilHvitfeldt/hcandersenr#2]
Because of the imported packages (`dplyr`, `magrittr`, and `rlang`), it takes a long time to install `hcandersenr` via `devtools::install_github("EmilHvitfeldt/hcandersenr")`.

I guess allowing `hca_fairytales.R` to live in a `data-raw` folder could reduce the dependency? That is, maybe `hca_fairytales` could be another `rda` file?

**Comment by EmilHvitfeldt** [comment]
Thanks for your feedback! 

I will look into it, but I don't see why it couldn't be done.
